# =============================================================================
# docker/f1tenth/docker-compose.yml
# =============================================================================

services:
  f1tenth_stack:
    build:
      context: ../../
      dockerfile: docker/f1tenth/Dockerfile
      network: host
    container_name: f1tenth_stack

    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia

    volumes:
      - ../../src:/ros2_ws/src
      - ../../scripts:/ros2_ws/scripts
      - zed_resources:/usr/local/zed/resources

    network_mode: "host"
    privileged: true
    tty: true
    stdin_open: true

volumes:
  zed_resources:
